-- AlterTable
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "colors" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "sizes" TEXT[] DEFAULT ARRAY[]::TEXT[];

-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "color" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "size" TEXT;
